<a href="https://colab.research.google.com/github/Karthikeyan-Analyst/pandas-practice/blob/Python_practice/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [65]:
import numpy as np
a = np.array([[1, 2, 3],
              [4, 5, 6]])
a.shape

TypeError: 'list' object is not callable

ARRAY

In [ ]:
a=np.array([1,2,3,4,5,6,7,8,])
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
a[2]

np.int64(3)

In [ ]:
a[3]=13
a

array([ 1,  2,  3, 13,  5,  6,  7,  8])

In [ ]:
a[:2]

array([1, 2])

In [ ]:
a[:4]

array([ 1,  2,  3, 13])

In [ ]:
a[:5]

array([ 1,  2,  3, 13,  5])

In [ ]:
b=a[:2]
b

array([1, 2])

In [ ]:
b[1]

np.int64(2)

In [ ]:
a=np.array(23)
print('No of dimension',a.ndim),
print('Shape',a.shape),
print('Length of shape',len(a.shape)),
print('size',a.size)

No of dimension 0
Shape ()
Length of shape 0
size 1


In [ ]:
a=np.array([23,12])
print('No of dimension',a.ndim),
print('Shape',a.shape),
print('Length of shape',len(a.shape)),
print('size',a.size)

No of dimension 1
Shape (2,)
Length of shape 1
size 2


In [ ]:
a=np.array([23,12,24,34])
print('No of dimension',a.ndim),
print('Shape',a.shape),
print('Length of shape',len(a.shape)),
print('size',a.size)

No of dimension 1
Shape (4,)
Length of shape 1
size 4


In [ ]:
a=np.array([[23,12],
           [15,16]])
print('No of dimension',a.ndim),
print('Shape',a.shape),
print('Length of shape',len(a.shape)),
print('size',a.size)

No of dimension 2
Shape (2, 2)
Length of shape 2
size 4


In [ ]:


a = np.array([
    [[23,12,17],
     [15,16,18]],

    [[9,8,7],
     [6,5,4]]
])

print('No of dimension',a.ndim),
print('Shape',a.shape),
print('Length of shape',len(a.shape)),
print('size',a.size)

No of dimension 3
Shape (2, 2, 3)
Length of shape 3
size 12


In [ ]:
a=np.array([1,2,3])
print('No of dimension',a.ndim),
print('Shape',a.shape),
print('Length of shape',len(a.shape)),
print('size',a.size)

No of dimension 1
Shape (3,)
Length of shape 1
size 3


In [ ]:
a=np.array([[1,2,3],
            [2,3,5]])
print('No of dimension',a.ndim),
print('Shape',a.shape),
print('Length of shape',len(a.shape)),
print('size',a.size)

No of dimension 2
Shape (2, 3)
Length of shape 2
size 6


In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
a.dtype

dtype('int64')

In [ ]:
np.zeros(9,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.zeros((2,3,7))

array([[[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]]])

In [ ]:
np.zeros((2,3,4,7))

array([[[[0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0.]]]])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.ones((2,3,3,9))

array([[[[1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1.]]]])

In [ ]:
np.empty(5)


array([1., 1., 1., 1., 1.])

In [ ]:
np.empty((2,3))

array([[4.98020289e-315, 0.00000000e+000, 0.00000000e+000],
       [7.25489181e-310, 1.38260575e-316, 2.56761523e-312]])

In [ ]:
np.arange(2,12,2)

array([ 2,  4,  6,  8, 10])

In [ ]:
np.arange(3,10,2)

array([3, 5, 7, 9])

In [ ]:
np.linspace(1,10,1)

array([1.])

In [ ]:
np.linspace(0,10,0)

array([], dtype=float64)

In [ ]:
np.linspace(2,20,5)

array([ 2. ,  6.5, 11. , 15.5, 20. ])

In [ ]:
arr=np.array([1,2,3,4,3,6,9,8,6])

In [ ]:
np.sort(arr)

array([1, 2, 3, 3, 4, 6, 6, 8, 9])

In [ ]:
arr=np.array=([99,98,78,46,23,20])


In [ ]:
np.sort(arr
        )

array([20, 23, 46, 78, 98, 99])

In [ ]:
import numpy as np

In [ ]:
a=10
b=10

In [ ]:
print(a+b)

20


In [ ]:
import numpy as np
print(np.array)
print(type(np.array))


[99, 98, 78, 46, 23, 20]
<class 'list'>


In [66]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
np.concatenate((a, b))

TypeError: 'list' object is not callable